services:
  # chat-service:
  #   build:
  #     context: services/chat-service/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - services/chat-service/.env
  #   networks:
  #     - chat-network
  
  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222"
    networks:
      - chat-network

  cassandra:
    image: cassandra:5.0.5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ChatCluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data:

networks:
  chat-network: