name: chat-server
services:
  chat-service:
    build:
      context: services/chat-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      chat-network:
        aliases:
          - chat.local
    depends_on:
      scylla:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: services/chat-service
          target: /app
        - action: rebuild
          path: services/chat-service/requirements.txt
          target: /app/requirements.txt

  message-service:
    build:
      context: services/message-service/
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - .env
    networks:
      chat-network:
        aliases:
          - message.local
    depends_on:
      scylla:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: services/message-service
          target: /app
        - action: rebuild
          path: services/message-service/requirements.txt
          target: /app/requirements.txt

  room-service:
    build:
      context: services/room-service/
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - .env
    networks:
      chat-network:
        aliases:
          - room.local
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: services/room-service
          target: /app
        - action: rebuild
          path: services/room-service/requirements.txt
          target: /app/requirements.txt

  user-service:
    build:
      context: services/user-service/
      dockerfile: Dockerfile
    ports:
      - "8020:8000"
    env_file:
      - .env
    networks:
      chat-network:
        aliases:
          - user.local
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: services/user-service
          target: /app
        - action: rebuild
          path: services/user-service/requirements.txt
          target: /app/requirements.txt

  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222"
    networks:
      chat-network:
        aliases:
          - nats.local

  scylla:
    image: scylladb/scylla:2025.2
    ports:
      - "9042:9042"
    environment:
      - SCYLLA_SEEDS=scylla
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      chat-network:
        aliases:
          - scylla.local
    
  keycloack:
    image: keycloak/keycloak:26.3
    ports:
      - 8080:8080
    command: start-dev --import-realm
    environment:
      - KC_DB_VENDOR=POSTGRES
      - KC_DB_ADDR=postgres
      - KC_DB_DATABASE=${KC_DB_DATABASE}
      - KC_DB_USER=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=localhost
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./shared/keycloack:/opt/keycloak/data/import
    networks:
      chat-network:
        aliases:
          - ${KC_HOSTNAME}

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${KC_DB_DATABASE}
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      chat-network:
        aliases:
          - postgres.local

volumes:
  scylla_data:
  postgres_data:

networks:
  chat-network:
