# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/message.proto\x12\x07message\"6\n\x13ListMessagesRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62\x65\x66ore\x18\x02 \x01(\t\"B\n\x14ListMessagesResponse\x12*\n\x08messages\x18\x01 \x03(\x0b\x32\x18.message.MessageResponse\"-\n\x17GetMessageStatusRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\">\n\x10MessagesResponse\x12*\n\x08messages\x18\x01 \x03(\x0b\x32\x18.message.MessageResponse\"\x92\x01\n\x0fMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\x12\x12\n\nupdated_at\x18\x07 \x01(\x03\x32\xae\x01\n\x0eMessageService\x12K\n\x0cListMessages\x12\x1c.message.ListMessagesRequest\x1a\x1d.message.ListMessagesResponse\x12O\n\x10GetMessageStatus\x12 .message.GetMessageStatusRequest\x1a\x19.message.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTMESSAGESREQUEST']._serialized_start=33
  _globals['_LISTMESSAGESREQUEST']._serialized_end=87
  _globals['_LISTMESSAGESRESPONSE']._serialized_start=89
  _globals['_LISTMESSAGESRESPONSE']._serialized_end=155
  _globals['_GETMESSAGESTATUSREQUEST']._serialized_start=157
  _globals['_GETMESSAGESTATUSREQUEST']._serialized_end=202
  _globals['_MESSAGESRESPONSE']._serialized_start=204
  _globals['_MESSAGESRESPONSE']._serialized_end=266
  _globals['_MESSAGERESPONSE']._serialized_start=269
  _globals['_MESSAGERESPONSE']._serialized_end=415
  _globals['_MESSAGESERVICE']._serialized_start=418
  _globals['_MESSAGESERVICE']._serialized_end=592
# @@protoc_insertion_point(module_scope)
