"""empty message

Revision ID: 62fa56c0db59
Revises: 
Create Date: 2025-08-28 13:13:50.795635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fa56c0db59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DIRECT', 'GROUP', 'CHANNEL', name='roomtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('last_message_preview', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_sender_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    op.drop_table('rooms')
    # ### end Alembic commands ###
